#生产环境
spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.190.89.122:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  # 配置jpa
  jpa:
    hibernate:
      # 数据库每次连接时 检查表结构与实体对象是否一致 若不一致同步成一致的
      ddl-auto: none
    # 在控制台和日志文件中显示 sql语句
    show-sql: true
# 配置日志
logging:
  level:
    # spring-boot 日志级别
    root: warn
    # com.zme 包下的代码的日志级别
    com.zme: info
  file: log/blog-pro.log
# 服务器端口号
server:
  port: 80